name: agritungotest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


#version: 1.0.0+1

environment:
  sdk: '>=2.19.0-96.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  fl_chart: ^0.55.1
  http: ^0.13.4
#  splashscreen: ^1.3.5
  filter_list: ^1.0.2
  awesome_dialog: ^2.1.1
  fluttertoast: ^8.0.8
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  substring_highlight: ^1.0.33
  api_cache_manager: ^1.0.2
  shared_preferences: ^2.0.15
  animated_splash_screen:
  sms_otp_auto_verify: ^2.0.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  geolocator: ^9.0.0
  location: ^4.2.0
  geocode: ^1.0.1
  geocoding: ^2.0.4
  smooth_page_indicator: ^1.0.0+2
#  intl: ^0.17.0
  flutter_pin_code_fields: ^1.1.0
  auto_size_text: ^3.0.0
  charts_flutter: ^0.12.0
  http_parser: ^4.0.1
  mime: ^1.0.2
  textfield_search: ^0.10.0
  flutter_typeahead: ^4.1.1
  localstorage: ^4.0.0+1
  flutter_native_splash: ^2.2.7
  flutter_svg: ^1.1.4
  country_code_picker: ^2.0.2
  in_app_review: ^2.0.4
  provider: ^6.0.3
  share_plus: ^4.0.5
  cached_network_image: ^3.2.1
#  open_file: ^3.2.1
  open_file_safe: ^3.2.3
  file_picker: ^4.6.1
  flutter_html_to_pdf: ^0.7.0
  permission_handler: ^10.0.0
  video_player: ^2.4.2
  #paytm: ^3.0.1
  youtube_player_flutter: ^8.1.0
  package_info: ^2.0.2
  url_launcher: ^6.1.2
  sqflite: ^2.0.2
  version: ^2.0.0
  flutter_downloader: ^1.8.0+1
  speech_to_text: ^5.5.0
  tuple: ^2.0.0
  lottie: ^1.4.2
  connectivity: ^3.0.6
  jaguar_jwt: ^3.0.0
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.10
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
#  sms_autofill: ^2.2.0
  shimmer: ^2.0.0
  badges: ^2.0.3
  #razorpay_flutter: ^1.3.2
  google_maps_flutter: ^2.2.0
  firebase_messaging: ^11.4.1
  firebase_auth: ^3.3.19
  firebase_dynamic_links: ^4.2.5
  flutter_widget_from_html: ^0.8.5
#  flutter_stripe: ^3.0.2
  cupertino_icons: ^1.0.4
  firebase_core: ^1.21.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line
  flutter_rating_bar: ^4.0.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - lib/Language/
    - assets/animation/
    - assets/agritungo.db

  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
    - family: ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Regular.ttf
